plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'dev.fedormaleev'
version = '0.0.1-SNAPSHOT'
description = 'leaderboard-service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // REST API, контроллеры, JSON, встроенный Tomcat
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    // @Valid, @NotBlank, @Positive и так далее
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // JPA, Hibernate, repositories, транзакции
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Миграции базы
    implementation 'org.springframework.boot:spring-boot-starter-flyway'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql'

    // PostgreSQL JDBC driver
    runtimeOnly 'org.postgresql:postgresql'

    // /actuator/health и /actuator/info
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    //redis driver
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // Тесты
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
